<table>
<tr>
<td rowspan = 2></td><td rowspan = 2>&nbsp;<img class=rtdbsupport src = 'rtdbsupport.gif' /></td><td class=bold>Support</td><td>(English; do not use Google translate, if do not speak English - write in the language that you know. If needed, my crypto key ( https://www.gpg4win.org/ ) is C64BE61A in keys.gnupg.net [0ADA 369A 692F 515F F4CC  6C2B D30A C753 C64B E61A])</td>
</tr><tr>
<td class=bold>Поддержка</td><td>(на русском. Если хотите шифровать переписку, мой GnuPG-ключ шифрования ( https://www.gpg4win.org/ ): C64BE61A на keys.gnupg.net [0ADA 369A 692F 515F F4CC  6C2B D30A C753 C64B E61A])</td>
</tr>
</table>